### ISSUE TITLE
Feature Request - Default font setting in the editor

### ISSUE THREAD

**Issue by renegadels** [playcanvas/editor#460]
Hello,

Please find the original forum thread [here](https://forum.playcanvas.com/t/set-default-font-when-have-multiple-fonts/21085). It would be great if we could select a default font in the project settings, it will make creating new text elements a lot easier and more convenient for developers.

Thanks!

**Comment by 403-Fruit** [comment]
In the meantime, if you have Stylus installed, that's what I'm using to change the font. You could also use a userscript to accomplish this.  

Here's the css I use to change the font to Fira Code and enable ligatures  

```css
@import url("https://cdn.jsdelivr.net/gh/tonsky/FiraCode@5/distr/fira_code.css");

.CodeMirror pre { 
    font-variant-ligatures: contextual !important; 
}

.cm-s-default.CodeMirror {
    background-color: #212121;
    font-variant-ligatures: contextual;
    font-family: 'Fira Code', monospace;
    font-size: 14px !important;
}
```
